routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/employee', 'App\Http\Controllers\EmployeesController');

app/Models/Employee.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'first_name',
        'last_name',
        'gender'
    ];

    public function address(){
        return $this->hasMany(Address::class, 'employee_id', 'id');
    }

    public function emails(){
        return $this->hasMany(Email::class);
    }

    public function phones(){
        return $this->hasMany(Phone::class);
    }

    public function whatsappContacts(){
        return $this->hasMany(Whatsapp::class);
    }

}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Address;
use App\Models\Email;
use App\Models\Employee;
use App\Models\Phone;
use App\Models\Whatsapp;
use Illuminate\Http\Request;

class EmployeesController extends Controller
{
    //

    public function index()
    {

        $employees = Employee::all();
        return view('employee.index', compact([
            'employees'
        ]));
    }

    public function store(Request $request)
    {
        $arrayW = explode('_', $request->whatsapp_primary[0]);
        $whatsapp_primary = $arrayW[2];
        $arrayP = explode('_', $request->phone_primary[0]);
        $phone_primary = $arrayP[2];
        $arrayE = explode('_', $request->email_primary[0]);
        $email_primary = $arrayE[2];
        // dd($request);


        $employee = Employee::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'gender' => $request->gender
        ]);
        $employee->address()->create([
            'location' => $request->location,
            'address1' => $request->address1,
            'address2' => $request->address2,
            'postal_code' => $request->postal_code,
            'taluka' => $request->taluka,
            'suburb' => $request->suburb,
            'city' => $request->city,
            'district' => $request->district,
            'state' => $request->state,
            'country' => $request->country
        ]);
        // if(count($request->whatsapp) < $whatsapp_primary){
        //     $whatsapp_primary--;
        // }
        $i = 1;
        foreach($request->whatsapp as $number){
            $whatsappData = [
                'whatsapp'=> $number,
            ];
            if($i == $whatsapp_primary){
                $whatsappData['primary'] = 1;
                // dd($whatsappData);
            }

            $employee->whatsappContacts()->create($whatsappData);
            $i++;
        }


        $i = 1;
        foreach($request->phone as $number){
            $phoneData = [
                'phone'=> $number,
                'employee_id' => $employee->id
            ];
            if($i == $phone_primary){
                $phoneData['primary'] = 1;
            }
            Phone::create($phoneData);
            $i++;
        }
        $i = 1;

        foreach($request->email as $mail){
            $emailData = [
                'email'=> $mail,
                'employee_id'=>$employee->id
            ];
            if($i == $email_primary){
                $emailData['primary'] = 1;
            }
            Email::create($emailData);
            $i++;
        }

        return redirect(route('employee.index'));



    }


    public function create(){
        return view('employee.create');
    }


    public function edit(Employee $employee)
    {

        $phones = $employee->phones;
        $address = $employee->address()->first();
        $whatsapp_phones = $employee->whatsappContacts;
        $emails = $employee->emails;

        return view('employee.edit', compact([
            'employee',
            'address',
            'phones',
            'whatsapp_phones',
            'emails'
        ]));
    }

    public function update(Request $request, Employee $employee)
    {
        // dd($request);
        $arrayW = explode('_', $request->whatsapp_primary[0]);
        $whatsapp_primary = $arrayW[2];
        $arrayP = explode('_', $request->phone_primary[0]);
        $phone_primary = $arrayP[2];
        $arrayE = explode('_', $request->email_primary[0]);
        $email_primary = $arrayE[2];




        $employee->address()->update([
            'location' => $request->location,
            'address1' => $request->address1,
            'address2' => $request->address2,
            'postal_code' => $request->postal_code,
            'taluka' => $request->taluka,
            'suburb' => $request->suburb,
            'city' => $request->city,
            'district' => $request->district,
            'state' => $request->state,
            'country' => $request->country
        ]);
        $employee->update([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'gender' => $request->gender
        ]);
        $employee->whatsappContacts()->forceDelete();
        $employee->emails()->forceDelete();
        $employee->phones()->forceDelete();
        $i = 1;
        foreach($request->whatsapp as $number){
            $whatsappData = [
                'whatsapp'=> $number,
            ];
            if($i == $whatsapp_primary){
                $whatsappData['primary'] = 1;
                // dd($whatsappData);
            }

            $employee->whatsappContacts()->create($whatsappData);
            $i++;
        }


        $i = 1;
        foreach($request->phone as $number){
            $phoneData = [
                'phone'=> $number
            ];
            if($i == $phone_primary){
                $phoneData['primary'] = 1;
            }
            $employee->phones()->create($phoneData);
            $i++;
        }
        $i = 1;

        foreach($request->email as $mail){
            $emailData = [
                'email'=> $mail
            ];
            if($i == $email_primary){
                $emailData['primary'] = 1;
            }
            $employee->emails()->create($emailData);
            $i++;
        }

        return redirect(route('employee.index'));



    }



    public function destroy(Employee $employee){
        $employee->address()->forceDelete();
        $employee->phones()->forceDelete();
        $employee->emails()->forceDelete();
        $employee->whatsappContacts()->forceDelete();
        $employee->delete();
        return redirect(route('employee.index'));
    }

}

resources/views/employee/create.blade.php
@extends("layouts.app")
@section('content')

<div class="card">
    <div class="card-header">Add Employee</div>
    <div class="card-body">
      <form action="{{ route('employee.store') }}" method="POST" id="myForm">
      @csrf
      <div class="row">
          <div class="col-md-4">
            <div class="form-group">
                <label for="last_name">first Name:</label>
                <input type="text" name="first_name" id="first_name">
              </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" name="last_name" id="last_name">
              </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
                <label for="gender">Gender:</label>
                <input type="text" name="gender" id="gender">
              </div>
          </div>
      </div>
      <h4>Address</h4>
      <div class="address-block">

      <div class="row">
      <div class="col-md-4">
      <label for="address">Address 1:</label>
      <input type="text" placeholder="address 1" name="address1" id="address1">
      </div>
      <div class="col-md-4">
      <label for="address">Address 2:</label>
      <input type="text" placeholder="address2" name="address2" id="address2">
      </div>
      <div class="col-md-4">
      <label for="address">Location:</label>
      <input type="text" placeholder="location" name="location" id="location">
      </div>
      </div>


      <div class="row">
      <div class="col-md-4">
      <label for="address">Postal area:</label>
      <input type="text" placeholder="postal_area" name="postal_area" id="postal_area">
      </div>
      <div class="col-md-4">
      <label for="address">postal code:</label>
      <input type="number" placeholder="postal_code" name="postal_code" id="postal_code">
      </div>
      <div class="col-md-4">
      <label for="address">Taluka:</label>
      <input type="text" placeholder="taluka" name="taluka" id="taluka">
      </div>
      </div>


      <div class="row">
      <div class="col-md-4">
      <label for="address">Suburb:</label>
      <input type="text" placeholder="suburb" name="suburb" id="suburb">
      </div>

      <div class="col-md-4">
      <label for="address">City:</label>
      <input type="text" placeholder="city" name="city" id="city">
      </div>
      </div>


      <div class="row">
      <div class="col-md-4">
      <label for="address">District:</label>
      <input type="text" placeholder="district" name="district" id="district">
      </div>
      <div class="col-md-4">
      <label for="address">State:</label>
      <input type="text" placeholder="state" name="state" id="state">
      </div>
      <div class="col-md-4">
      <label for="address">Country:</label>
      <input type="text" placeholder="country" name="country" id="country">
      </div>
      </div>

      </div>


      <h4>Contact Details:</h4>
      <div class="row">
      <div class="col-md-4" id="phone-adder">
      <div class="heading d-flex justify-content-between">
      <h6>Contacts</h6>
      <button class="btn btn-outline-primary" class="phone-add" onclick="phoneAdd()" type="button">+</button>

      </div>


      </div>
      <div class="col-md-4" id="whatsapp-contact-adder">
      <div class="heading d-flex justify-content-between">
      <h6>Whatsapp Contacts</h6>
      <button class="btn btn-outline-primary" class="whatsapp-contact-add" onclick="whatsappContactAdd()" type="button">+</button>
      </div>

      </div>

      <div class="col-md-4" id="email-adder">
      <div class="heading d-flex justify-content-between">
      <h6>Email</h6>
      <button class="btn btn-outline-primary" class="email-add" onclick="emailAdd()" type="button">+</button>
      </div>


      </div>
      </div>

      <div class="card-footer">
      <button type="submit" class="btn btn-primary" id="btn-submit">Save</button>
      </div>
      </form>
      </div>
    </div>

@endsection

@section('page-level-scripts')

<script>
    i = 1;
    function phoneAdd(){
      $("#phone-adder").append(`<div id='contact-field' class='row'><button type='button' class='contact-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='contacts'>Contact:</label><input type='number' name='phone[]' id='contact'><label for='is_primary'>primary: </label><input type='radio' name='phone_primary[]' value='phone_primary_${i}'></div>`);
      i++;
    }
    j=1
    function whatsappContactAdd(){
      $("#whatsapp-contact-adder").append(`<div id='whatsapp-contact-field' class='row'><button type='button' class='whatsapp-contact-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='whatsapp'>Whatsapp:</label><input type='number' name='whatsapp[]' id='whatsapp'><label for='is_primary'>primary: </label><input type='radio' name='whatsapp_primary[]' value='whatsapp_primary_${j}'></div>`);
        j++;
    }
    k = 1
    function emailAdd(){
      $("#email-adder").append(`<div id='email-field' class='row'><button type='button' class='email-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='email'>Email:</label><input type='email' name='email[]' id='email'><label for='is_primary'>primary: </label><input type='radio' name='email_primary[]' value='email_primary_${k}'></div>`);
        k++;
    }

    function valueDelete(value){
      console.log($(value));


      $(value).parent().remove();
      if($(value).hasClass("contact-delete")){
          console.log($("input[name='phone_primary[]']"));
          $("input[name='phone_primary[]']").each(function(index){
              i = index + 1;
            $(this).val('phone_primary_' + i);
          });
      }else if($(value).hasClass("whatsapp-contact-delete")){
          console.log($("input[name='whatsapp_primary[]']"));
          $("input[name='whatsapp_primary[]']").each(function(index){
              i = index + 1;
            $(this).val('whatsapp_primary_' + i);
          });
      }else if($(value).hasClass("email-delete")){
          console.log($("input[name='email_primary[]']"));
          $("input[name='email_primary[]']").each(function(index){
              i = index + 1;
            $(this).val('email_primary_' + i);
          });
      }
    }

</script>
@endsection

resources/views/employee/edit.blade.php
@extends("layouts.app")
@section('content')

<div class="card">
    <div class="card-header">Edit Employee</div>
    <div class="card-body">
        <form action="{{ route('employee.update', $employee->id) }}" method="POST" id="myForm">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="first_name">First Name:</label>
                        <input type="text" name="first_name" id="first_name" value="{{ $employee->first_name }}">
                      </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="last_name">Last Name:</label>
                        <input type="text" name="last_name" id="last_name" value="{{ $employee->last_name }}">
                      </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="gender">Gender:</label>
                        <input type="text" name="gender" id="gender" value="{{ $employee->gender }}">
                      </div>
                </div>
            </div>
            <h4>Address</h4>
            <div class="address-block">

            <div class="row">
            <div class="col-4">
            <label for="address">Address 1:</label>
            <input type="text" placeholder="address 1" name="address1" id="address1" value="{{ ($address->address1) }}">
            </div>
            <div class="col-4">
            <label for="address">Address 2:</label>
            <input type="text" placeholder="address2" name="address2" id="address2" value="{{ $address->address2 }}">
            </div>
            <div class="col-4">
            <label for="address">Location:</label>
            <input type="text" placeholder="location" name="location" id="location" value="{{ $address->location }}">
            </div>
            </div>


            <div class="row">
            <div class="col-4">
            <label for="address">postal code:</label>
            <input type="number" placeholder="postal_code" name="postal_code" id="postal_code" value="{{ $address->postal_code }}">
            </div>
            <div class="col-4">
            <label for="address">Taluka:</label>
            <input type="text" placeholder="taluka" name="taluka" id="taluka" value="{{ $address->taluka }}">
            </div>
            </div>


            <div class="row">
            <div class="col-4">
            <label for="address">Suburb:</label>
            <input type="text" placeholder="suburb" name="suburb" id="suburb" value="{{ $address->suburb }}">
            </div>
            <div class="col-4">
            <label for="address">City:</label>
            <input type="text" placeholder="city" name="city" id="city" value="{{ $address->city }}">
            </div>
            </div>


            <div class="row">
            <div class="col-4">
            <label for="address">District:</label>
            <input type="text" placeholder="district" name="district" id="district" value="{{ $address->district }}">
            </div>
            <div class="col-4">
            <label for="address">State:</label>
            <input type="text" placeholder="state" name="state" id="state" value="{{ $address->state }}">
            </div>
            <div class="col-4">
            <label for="address">Country:</label>
            <input type="text" placeholder="country" name="country" id="country" value="{{ $address->country }}">
            </div>
            </div>

            </div>


            <h4>Contact Details:</h4>
            <div class="row">
            <div class="col-md-4" id="phone-adder">
            <div class="heading d-flex justify-content-between">
            <h6>Contacts</h6>
            <button class="btn btn-outline-primary" class="phone-add" onclick="phoneAdd()" type="button">+</button>
            </div>
            <?php $i = 1 ?>
            @foreach($phones as $phone)
            <div id='phone-field' class='row'><button type='button' class='contact-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='phones'>Contact:</label><input type='number' name='phone[]' id='phone' value="{{ $phone->phone}}"><label for='is_primary'>primary: </label><input type='radio' name='phone_primary[]'  {{ $phone->is_primary }} value="phone_primary_<?=$i?>"></div>
            <?php $i++ ?>
            @endforeach

            </div>
            <div class="col-md-4" id="whatsapp-contact-adder">
            <div class="heading d-flex justify-content-between">
            <h6>Whatsapp Contacts</h6>
            <button class="btn btn-outline-primary" class="whatsapp-contact-add" onclick="whatsappContactAdd()" type="button">+</button>
            </div>
            <?php $i = 1 ?>
            @foreach($whatsapp_phones as $whatsapp)
            <div id='contact-field' class='row'><button type='button' class='whatsapp-contact-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='phones'>Whatsapp:</label><input type='number' name='whatsapp[]' id='whatsapp' value="{{ $whatsapp->whatsapp}}"><label for='is_primary'>primary: </label><input type='radio' name='whatsapp_primary[]'  {{ $whatsapp->is_primary }} value="whatsapp_primary_<?=$i?>"></div>
            <?php $i++ ?>
            @endforeach

            </div>

            <div class="col-md-4" id="email-adder">
            <div class="heading d-flex justify-content-between">
            <h6>Email</h6>
            <button class="btn btn-outline-primary" class="email-add" onclick="emailAdd()" type="button">+</button>
            </div>
            <?php $i = 1 ?>
            @foreach($emails as $mail)

            <div id='contact-field' class='row'><button type='button' class='email-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='phones'>Email:</label><input type='email' name='email[]' id='email' value="{{ $mail->email }}"><label for='is_primary'>primary: </label><input type='radio' name='email_primary[]'  {{ $mail->is_primary }} value="email_primary_<?=$i?>"></div>
            <?php $i++ ?>
            @endforeach


            </div>
            </div>

            <div class="card-footer">
            <button type="submit" class="btn btn-primary" id="btn-submit">Save</button>
            </div>
            </form>

      </div>
    </div>

@endsection

@section('page-level-scripts')

<script>
    i = 1;
    function phoneAdd(){
      $("#phone-adder").append(`<div id='phone-field' class='row'><button type='button' class='contact-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='phones'>Contact:</label><input type='number' name='phone[]' id='phone'><label for='is_primary'>primary: </label><input type='radio' name='phone_primary[]' value='phone_primary_${i}'></div>`);
      i++;
    }
    j=1
    function whatsappContactAdd(){
      $("#whatsapp-contact-adder").append(`<div id='whatsapp-contact-field' class='row'><button type='button' class='whatsapp-contact-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='whatsapp'>Whatsapp:</label><input type='number' name='whatsapp[]' id='whatsapp'><label for='is_primary'>primary: </label><input type='radio' name='whatsapp_primary[]' value='whatsapp_primary_${j}'></div>`);
        j++;
    }
    k = 1
    function emailAdd(){
      $("#email-adder").append(`<div id='email-field' class='row'><button type='button' class='email-delete' onclick='valueDelete(this)'><i class='fa fa-trash'></i></button><label for='email'>Email:</label><input type='email' name='email[]' id='email'><label for='is_primary'>primary: </label><input type='radio' name='email_primary[]' value='email_primary_${k}'></div>`);
        k++;
    }

    function valueDelete(value){
    //   console.log($(value));
      $(value).parent().remove();
      if($(value).hasClass("contact-delete")){
          console.log($("input[name='phone_primary[]']"));
          $("input[name='phone_primary[]']").each(function(index){
              i = index + 1;
            $(this).val('phone_primary_' + i);
          });
      }else if($(value).hasClass("whatsapp-contact-delete")){
          console.log($("input[name='whatsapp_primary[]']"));
          $("input[name='whatsapp_primary[]']").each(function(index){
              i = index + 1;
            $(this).val('whatsapp_primary_' + i);
          });
      }else if($(value).hasClass("email-delete")){
          console.log($("input[name='email_primary[]']"));
          $("input[name='email_primary[]']").each(function(index){
              i = index + 1;
            $(this).val('email_primary_' + i);
          });
      }
    }

</script>
@endsection

resources/views/employee/index.blade.php
@extends("layouts.app")
@section('content')

    <div class="d-flex justify-content-end">
        <a href="{{ route('employee.create') }}" class="btn btn-primary">Add Employee</a>
    </div>
    <div class="card">
        <div class="card-header">Employees</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Name</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach ($employees as $employee)
                        <tr>
                            <td><?= "$employee->first_name $employee->last_name"?></td>
                            <td><a href="{{ route('employee.edit', $employee->id) }}" class="btn btn-primary btn-sm">Edit</a><a href="" class="btn btn-danger btn-sm" onclick="displayModalForm({{$employee}})" data-toggle="modal" data-target="#deleteModal">Delete</a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
              <div class="modal-body">
                <p>Are you sure you want to delete Category?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    <!-- / DELETE MODAL-->
@endsection

@section('page-level-scripts')

<script>
    function displayModalForm($employee) {
        var url = "/employee/"+$employee.id;
        $("#deleteForm").attr('action', url);
    }
</script>
@endsection